Details popup window
hamid-murambiwa/Portfolio pull request #14
Opened 2021-09-01 19:49 UTC by hamid-murambiwa

In this project, I had to implement a popup window that includes the project details on both desktop and mobile.
*Add  a modal to the index.html file
*Add a modal algorithm to the script.js file 
*Removed the modal content from the index.html file into the script.js file
*Removed the content in the project card section from index.html into the script.js file.

2021-09-01 21:47 UTC, rukundoeric requested changes
Hi  @hamid-murambiwa, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +}
- [x] <b>REQUIRED:</b> This is not the correct way to add list of projects in `projectCards` content.
     - First of all, you need to initialize projects in an array of more than one project. 
        ```Javascript
               const projects = [
                  {
                       name: "Submarine game",
                       description: "A Phaser3 plataformer game built as part of the Microverse JavaScript program.",
                       image: "link_to_image.jpg",
                       technologies: ["Phaser3", "JavaScript", "Jest"],
                       link: "link_to_live_version.com",
                },
                  {
                       name: "calculator",
                       description: "calculator project.",
                       image: "link_to_image.jpg",
                       technologies: ["JavaScript", "Jest"],
                       link: "link_to_live_version.com",
                } 
                ]

        ```
    - Then iterate through the above array and append the content to `projectCards`.

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +pB2.innerHTML = desktopdesktopPopUp;
- [x] <b>REQUIRED:</b> Whether it is desktop or mobile, Modal popup data should be populated with the data from the selected project which is from the projects array. what you have here is not correct because it will always show the same content.
- [x] <b>REQUIRED:</b> And you don't have to use two separate PopUps since you can use just one and make it responsive with CSS.

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +};
- [ ] <b>REQUIRED:</b> You don't need this. just make sure that every data you need about each project is included in each item of the projects list array.

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +    }
- [ ] <b>REQUIRED:</b> As I said above, you don't need to check whether you are on desktop or mobile just to use a different modal, you can use one and let CSS take care of the rest.

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +    document.getElementById('modal').style = 'display: none';
- [ ] <b>REQUIRED:</b> The same as here, you don't need to check whether you are on desktop or mobile just to use a different modal, you can use one and let CSS take care of the rest.

2021-09-01 21:47 UTC, rukundoeric commented on script.js
> +  }
- [ ] <b>REQUIRED:</b> The same as here, you don't need to check whether you are on desktop or mobile just to use a different modal, you can use one and let CSS take care of the rest.

2021-09-02 10:54 UTC, dasileker approved these changes
### **Hi @hamid-murambiwa** 

### **Project Approved ✅**

![Approved](https://user-images.githubusercontent.com/61562626/131831512-ca204c9f-2f01-43b2-a3b3-0ed2fcb37a6b.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-02 11:03 UTC, merged